// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jsontext$0 from "../../../encoding/json/jsontext/models.js";

/**
 * Settings 前端提交的设置表单（apiKey/sshPassword 留空表示不修改）。
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * 只写字段：UI → 后端；后端永不回传
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("dockerIp" in $$source)) {
            /**
             * 留空=本机；填写则走 SSH
             * @member
             * @type {string}
             */
            this["dockerIp"] = "";
        }
        if (!("dockerPort" in $$source)) {
            /**
             * 默认 22
             * @member
             * @type {string}
             */
            this["dockerPort"] = "";
        }
        if (!("dockerUser" in $$source)) {
            /**
             * SSH 用户名
             * @member
             * @type {string}
             */
            this["dockerUser"] = "";
        }
        if (!("sshPassword" in $$source)) {
            /**
             * 只写字段：SSH 登录密码，留空=不修改
             * @member
             * @type {string}
             */
            this["sshPassword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * SettingsView 返回给前端的设置视图（不含明文 Key，只告知"是否已设置"）。
 */
export class SettingsView {
    /**
     * Creates a new SettingsView instance.
     * @param {Partial<SettingsView>} [$$source = {}] - The source object to create the SettingsView.
     */
    constructor($$source = {}) {
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("apiKeySet" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["apiKeySet"] = false;
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("dockerIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dockerIp"] = "";
        }
        if (!("dockerPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dockerPort"] = "";
        }
        if (!("dockerUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dockerUser"] = "";
        }
        if (!("sshPasswordSet" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sshPasswordSet"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsView(/** @type {Partial<SettingsView>} */($$parsedSource));
    }
}

/**
 * SkillInfo 单个技能的展示元数据（前端技能卡片与介绍弹窗的数据源）。
 */
export class SkillInfo {
    /**
     * Creates a new SkillInfo instance.
     * @param {Partial<SkillInfo>} [$$source = {}] - The source object to create the SkillInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 技能名（下划线命名空间，如 ops_list_containers）
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 描述全文（部署技能含动态流程清单，实时值）
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("parameters" in $$source)) {
            /**
             * Parameters 参数的 JSON Schema 原样透传（function-calling 定义）。
             * json.RawMessage 序列化时内嵌为真正的 JSON 对象，前端拿到的就是
             * {type, properties, required, ...} 结构，无需二次解析。
             * @member
             * @type {json$0.RawMessage}
             */
            this["parameters"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo(/** @type {Partial<SkillInfo>} */($$parsedSource));
    }
}
