// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jsontext$0 from "../../../encoding/json/jsontext/models.js";

/**
 * AgentDetail 单个智能体的管理明细（智能体管理弹窗列表卡片与详情的数据源）。
 */
export class AgentDetail {
    /**
     * Creates a new AgentDetail instance.
     * @param {Partial<AgentDetail>} [$$source = {}] - The source object to create the AgentDetail.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("systemPrompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemPrompt"] = "";
        }
        if (!("builtin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["builtin"] = false;
        }
        if (!("skills" in $$source)) {
            /**
             * 已装配技能（卡片计数与详情回显）
             * @member
             * @type {AgentSkillInfo[]}
             */
            this["skills"] = [];
        }
        if (!("availableSkills" in $$source)) {
            /**
             * 可选技能全集（装配区复选列表，含分类标记）
             * @member
             * @type {AgentSkillInfo[]}
             */
            this["availableSkills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentDetail}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField5_0($$parsedSource["skills"]);
        }
        if ("availableSkills" in $$parsedSource) {
            $$parsedSource["availableSkills"] = $$createField6_0($$parsedSource["availableSkills"]);
        }
        return new AgentDetail(/** @type {Partial<AgentDetail>} */($$parsedSource));
    }
}

/**
 * AgentSkillInfo 装配区/已装配列表中单个技能的展示元数据。
 */
export class AgentSkillInfo {
    /**
     * Creates a new AgentSkillInfo instance.
     * @param {Partial<AgentSkillInfo>} [$$source = {}] - The source object to create the AgentSkillInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 描述（实时值；部署技能含动态流程清单）
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("builtin" in $$source)) {
            /**
             * Builtin 分类标记：内置/自定义。来自技能注册表侧（Registry.IsBuiltin），
             * 本期全部内置；为下期自定义技能预留，前端只认标记不按名字判断。
             * @member
             * @type {boolean}
             */
            this["builtin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentSkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentSkillInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentSkillInfo(/** @type {Partial<AgentSkillInfo>} */($$parsedSource));
    }
}

/**
 * Settings 前端提交的设置表单（apiKey/sshPassword 留空表示不修改）。
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * 只写字段：UI → 后端；后端永不回传
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("dockerIp" in $$source)) {
            /**
             * 留空=本机；填写则走 SSH
             * @member
             * @type {string}
             */
            this["dockerIp"] = "";
        }
        if (!("dockerPort" in $$source)) {
            /**
             * 默认 22
             * @member
             * @type {string}
             */
            this["dockerPort"] = "";
        }
        if (!("dockerUser" in $$source)) {
            /**
             * SSH 用户名
             * @member
             * @type {string}
             */
            this["dockerUser"] = "";
        }
        if (!("sshPassword" in $$source)) {
            /**
             * 只写字段：SSH 登录密码，留空=不修改
             * @member
             * @type {string}
             */
            this["sshPassword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * SettingsView 返回给前端的设置视图（不含明文 Key，只告知"是否已设置"）。
 */
export class SettingsView {
    /**
     * Creates a new SettingsView instance.
     * @param {Partial<SettingsView>} [$$source = {}] - The source object to create the SettingsView.
     */
    constructor($$source = {}) {
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("apiKeySet" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["apiKeySet"] = false;
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("dockerIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dockerIp"] = "";
        }
        if (!("dockerPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dockerPort"] = "";
        }
        if (!("dockerUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dockerUser"] = "";
        }
        if (!("sshPasswordSet" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sshPasswordSet"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsView(/** @type {Partial<SettingsView>} */($$parsedSource));
    }
}

/**
 * SkillInfo 单个技能的展示元数据（前端技能视图卡片与详情弹窗的数据源）。
 */
export class SkillInfo {
    /**
     * Creates a new SkillInfo instance.
     * @param {Partial<SkillInfo>} [$$source = {}] - The source object to create the SkillInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 技能名（下划线命名空间，如 ops_list_containers）
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 描述全文（部署技能含动态流程清单，实时值）
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("builtin" in $$source)) {
            /**
             * Builtin 分类标记：内置/自定义。与 AgentSkillInfo.Builtin 同源
             * （技能注册表侧 Registry.IsBuiltin），前端只认标记不按名字判断；
             * 本期全部内置，为下期自定义技能预留。
             * @member
             * @type {boolean}
             */
            this["builtin"] = false;
        }
        if (!("parameters" in $$source)) {
            /**
             * Parameters 参数的 JSON Schema 原样透传（function-calling 定义）。
             * json.RawMessage 序列化时内嵌为真正的 JSON 对象，前端拿到的就是
             * {type, properties, required, ...} 结构，无需二次解析。
             * @member
             * @type {json$0.RawMessage}
             */
            this["parameters"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo(/** @type {Partial<SkillInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AgentSkillInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
