// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是 Wails 绑定对象（≈ Controller）。
 * 大写开头的方法会被自动生成前端绑定；每个方法只做一件事：转发给 svc（薄 Controller 原则）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appsvc$0 from "./internal/appsvc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * ApproveDeployment 批准部署审批单：校验门禁通过后异步执行，进度经聊天流帧推送。
 * 未批准/已拒绝/已过期的单子在这里都会被拒绝（代码强制门禁）。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ApproveDeployment(id) {
    return $Call.ByID(214032249, id);
}

/**
 * CancelTurn 取消该会话进行中的回合（前端流式期间的"停止"按钮）。
 * 幂等：没有进行中回合时静默成功。前端：CancelTurn(sessionID)
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CancelTurn(sessionID) {
    return $Call.ByID(2865305064, sessionID);
}

/**
 * DeleteDeployFlow 删除部署流程（执行历史保留）。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDeployFlow(id) {
    return $Call.ByID(2628816881, id);
}

/**
 * DeleteSession 删除会话及其全部消息。前端：DeleteSession(id)
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(id) {
    return $Call.ByID(3306942022, id);
}

/**
 * GetMessages 取会话历史消息。前端：GetMessages(sessionID)
 * @param {string} sessionID
 * @returns {$CancellablePromise<store$0.Message[]>}
 */
export function GetMessages(sessionID) {
    return $Call.ByID(3832618599, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSettings 读设置（API Key 只回传"是否已设置"，绝不回传明文）。
 * @returns {$CancellablePromise<appsvc$0.SettingsView>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListAgents 所有 Agent 定义（含挂载的技能列表）。前端：ListAgents()
 * @returns {$CancellablePromise<store$0.AgentRow[]>}
 */
export function ListAgents() {
    return $Call.ByID(578673379).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListAgentsDetail 智能体管理明细列表（基本信息 + 已装配技能 + 可选技能全集，
 * 技能带内置/自定义分类标记）。前端：ListAgentsDetail()
 * @returns {$CancellablePromise<appsvc$0.AgentDetail[]>}
 */
export function ListAgentsDetail() {
    return $Call.ByID(655126258).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListDeployFlows 部署流程列表（设置页管理区）。
 * @returns {$CancellablePromise<store$0.DeployFlow[]>}
 */
export function ListDeployFlows() {
    return $Call.ByID(1498518071).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListSessions 会话列表（按更新时间倒序）。前端：ListSessions()
 * @returns {$CancellablePromise<store$0.Session[]>}
 */
export function ListSessions() {
    return $Call.ByID(827108744).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ListSkills 全部技能的元数据（名称/描述/参数 Schema，按名排序）。
 * 设置页"技能管理"区的数据源；部署技能的描述为实时动态值（含当前流程清单）。
 * 前端：ListSkills()
 * @returns {$CancellablePromise<appsvc$0.SkillInfo[]>}
 */
export function ListSkills() {
    return $Call.ByID(1140726611).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * NewSession 创建新会话（默认绑定运维 Agent）。前端：NewSession()
 * @returns {$CancellablePromise<store$0.Session>}
 */
export function NewSession() {
    return $Call.ByID(2850677243).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * RejectDeployment 拒绝部署审批单（绝不执行）。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RejectDeployment(id) {
    return $Call.ByID(4114365077, id);
}

/**
 * SaveAgent 保存智能体信息（名称/模型/系统提示词；名称非空校验在编排层）。
 * 前端：SaveAgent(id, name, model, systemPrompt)
 * @param {string} id
 * @param {string} name
 * @param {string} model
 * @param {string} systemPrompt
 * @returns {$CancellablePromise<void>}
 */
export function SaveAgent(id, name, model, systemPrompt) {
    return $Call.ByID(3768442673, id, name, model, systemPrompt);
}

/**
 * SaveDeployFlow 新建/更新部署流程（ID=0 表示新建）。保存前做业务校验。
 * @param {store$0.DeployFlow} flow
 * @returns {$CancellablePromise<void>}
 */
export function SaveDeployFlow(flow) {
    return $Call.ByID(2911112271, flow);
}

/**
 * SaveSettings 保存设置；apiKey 为空字符串表示"保持原值不变"。
 * @param {appsvc$0.Settings} $in
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings($in) {
    return $Call.ByID(1949631069, $in);
}

/**
 * SendMessage 发送一条用户消息并同步执行完整 Agent 回合。
 * 注意：这是阻塞调用——前端 await 它直到整个回合结束；
 * 期间的流式增量通过聊天流（chat:delta / chat:tool / chat:done 帧）异步推送。
 * @param {string} sessionID
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(sessionID, text) {
    return $Call.ByID(1496882310, sessionID, text);
}

/**
 * SetAgentSkills 整组替换智能体的技能装配；落库即生效（Runner 每回合实时读，
 * 下轮对话工具列表自动变化，无需通知聊天侧）。前端：SetAgentSkills(id, skillNames)
 * @param {string} id
 * @param {string[]} skillNames
 * @returns {$CancellablePromise<void>}
 */
export function SetAgentSkills(id, skillNames) {
    return $Call.ByID(2072536338, id, skillNames);
}

/**
 * SetSessionAgent 切换会话绑定的 Agent。前端：SetSessionAgent(sessionID, agentID)
 * @param {string} sessionID
 * @param {string} agentID
 * @returns {$CancellablePromise<void>}
 */
export function SetSessionAgent(sessionID, agentID) {
    return $Call.ByID(1149337382, sessionID, agentID);
}

/**
 * TestLLM 测试 LLM 连接（发一条 "ping"）。
 * @returns {$CancellablePromise<void>}
 */
export function TestLLM() {
    return $Call.ByID(2685437664);
}

/**
 * TestSSH 用表单当前值测试连接（IP 留空测本机；否则 SSH 登录远端执行 docker version）。
 * @param {string} ip
 * @param {string} port
 * @param {string} user
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function TestSSH(ip, port, user, password) {
    return $Call.ByID(4121859417, ip, port, user, password);
}

// Private type creation functions
const $$createType0 = store$0.Message.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = appsvc$0.SettingsView.createFrom;
const $$createType3 = store$0.AgentRow.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = appsvc$0.AgentDetail.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = store$0.DeployFlow.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = store$0.Session.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = appsvc$0.SkillInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
