// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AgentRow Agent 定义实体（对应 agents + agent_skills 两张表）。
 */
export class AgentRow {
    /**
     * Creates a new AgentRow instance.
     * @param {Partial<AgentRow>} [$$source = {}] - The source object to create the AgentRow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("systemPrompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemPrompt"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("builtin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["builtin"] = false;
        }
        if (!("skills" in $$source)) {
            /**
             * 挂载的技能名列表（从中间表聚合而来）
             * @member
             * @type {string[]}
             */
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentRow}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField5_0($$parsedSource["skills"]);
        }
        return new AgentRow(/** @type {Partial<AgentRow>} */($$parsedSource));
    }
}

/**
 * DeployFlow 部署流程定义（声明式：参数声明 + 有序命令步骤模板）。
 * 步骤命令里的 {{参数名}} 占位符在执行前经转义后替换（见 shellx 包）。
 */
export class DeployFlow {
    /**
     * Creates a new DeployFlow instance.
     * @param {Partial<DeployFlow>} [$$source = {}] - The source object to create the DeployFlow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * TargetLocal | TargetSSH
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("params" in $$source)) {
            /**
             * @member
             * @type {FlowParam[]}
             */
            this["params"] = [];
        }
        if (!("steps" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["steps"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployFlow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeployFlow}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField4_0($$parsedSource["params"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField5_0($$parsedSource["steps"]);
        }
        return new DeployFlow(/** @type {Partial<DeployFlow>} */($$parsedSource));
    }
}

/**
 * FlowParam 流程参数声明：名字 + 说明 + 可选校验正则（全匹配语义）。
 */
export class FlowParam {
    /**
     * Creates a new FlowParam instance.
     * @param {Partial<FlowParam>} [$$source = {}] - The source object to create the FlowParam.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("desc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desc"] = "";
        }
        if (!("pattern" in $$source)) {
            /**
             * 为空 = 不做正则校验
             * @member
             * @type {string}
             */
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlowParam instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FlowParam}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlowParam(/** @type {Partial<FlowParam>} */($$parsedSource));
    }
}

/**
 * Message 消息实体。
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * user | assistant | tool
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * Session 会话实体。反引号里的是 struct tag：
 * `json:"id"` 告诉 JSON 序列化器字段名叫 id（≈ Jackson 的 @JsonProperty("id")）。
 * Wails 把 Go 对象传给前端时就是按这些 tag 序列化的。
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("agentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentId"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FlowParam.createFrom;
const $$createType2 = $Create.Array($$createType1);
